#!/bin/bash
# agent-pr.sh — Robust PR workflow for agents.
# Usage: agent-pr.sh "type: description" "PR body"
# Run from inside the repo.

set -euo pipefail

TITLE="${1:?Usage: agent-pr.sh 'type: title' 'PR body'}"
BODY="${2:-Auto-generated by agent}"

# Generate unique branch name: agent/$(uuid truncated)
BRANCH="agent/$(uuidgen 2>/dev/null || echo "$(date +%s)-$$")"

# Ensure we're in a git repo
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "❌ Not a git repository"
  exit 1
fi

# Stage all tracked files (not .env, node_modules, etc)
echo "📦 Staging changes..."
git add -A

# Check if there are changes
if git diff --cached --quiet; then
  echo "⚠️  No changes to commit"
  exit 0
fi

# Create or update branch
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "🔄 Branch $BRANCH exists, checking out..."
  git checkout "$BRANCH"
  git pull origin "$BRANCH" --rebase || true
else
  echo "🌿 Creating branch: $BRANCH"
  git checkout -b "$BRANCH"
fi

# Commit
echo "💾 Committing..."
git commit -m "$TITLE" || { echo "❌ Commit failed"; exit 1; }

# Push with retry
echo "📤 Pushing..."
git push -u origin "$BRANCH" --force-with-lease || { 
  echo "❌ Push failed (retrying once)..."
  sleep 2
  git push -u origin "$BRANCH" --force
}

# Create PR (idempotent — don't duplicate)
echo "🔗 Creating PR..."
EXISTING_PR=$(gh pr list --head "$BRANCH" --json number --jq '.[0].number' 2>/dev/null || echo "")

if [ -n "$EXISTING_PR" ]; then
  echo "✅ PR already exists: #$EXISTING_PR"
  PR_NUM="$EXISTING_PR"
else
  PR_URL=$(gh pr create --title "$TITLE" --body "$BODY" --base main --head "$BRANCH" 2>&1)
  PR_NUM=$(echo "$PR_URL" | grep -oP '/pull/\K[0-9]+' || echo "")
  echo "✅ PR created: $PR_URL"
fi

# Output for automation
echo ""
echo "::set-output name=branch::$BRANCH"
echo "::set-output name=pr::$PR_NUM"
echo "::set-output name=url::https://github.com/$(git remote get-url origin | sed 's/.*github.com[/:]//' | sed 's/\.git$//')/pull/$PR_NUM"

# Wait for CI checks (if enabled)
echo "⏳ Waiting for CI checks..."
gh pr checks "$PR_NUM" --wait || true

echo ""
echo "✅ Done. PR: https://github.com/$(git remote get-url origin | sed 's/.*github.com[/:]//' | sed 's/\.git$//')/pull/$PR_NUM"
